providers = ["ruby"]

[phases.setup]
aptPkgs = ["...", "libreoffice", "ghostscript", "poppler-utils", "imagemagick", "fontconfig", "default-jre"]

[phases.install_fonts]
dependsOn = ["setup"]
cmds = [
  "echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | debconf-set-selections",
  "DEBIAN_FRONTEND=noninteractive apt-get install -y ttf-mscorefonts-installer",
  "fc-cache -f -v"
]

[phases.fix_imagemagick_policy]
dependsOn = ["setup"]
cmds = [
  "./bin/fix_imagemagick_policy.sh"
]

[phases.install]
dependsOn = ["setup", "install_fonts", "fix_imagemagick_policy"]
